# Generated by Django 4.2.6 on 2024-01-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
