# Generated by Django 4.2.6 on 2024-01-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_remove_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
